snowflake_user = "ANU"
snowflake_password = "Anu@1802"
snowflake_account = "NGB31779"
snowflake_warehouse = "COMPUTE_WH"
snowflake_database = "CALLTIX_DB"
snowflake_schema = "CALLTIX_SC"
stage_name = "CALLTIX_STG"